### ISSUE TITLE
tables missing

### ISSUE THREAD

**Issue by pcouas** [TheCaffeineDev/Real-Estate-Django-Web-App#9]
Hi

I have created database and launched python manage.py runserver, but tables structures are missing ?
Do you have sql files for creating tables ?

Regards
Phil

**Comment by TheCaffeineDev** [comment]
Hi @pcouas 

You need to do the migrations first to get the table structure

```
python manage.py makemigrations
python manage.py migrate
```

But the data you have to create on your own.

**Comment by pcouas** [comment]
Ok, i could see all tables. But effectively all records in all tables are empty

Regards

**Comment by TheCaffeineDev** [comment]
Hi @pcouas  You need to fill the tables on your own. I don't have the database with me now. But it should be pretty much easy for you to fill the data in admin panel.
